language: objective-c

before_install:
# print version of os x
#- sw_vers
#install xctool
- brew update
- brew remove xctool
- brew install xctool
- chmod +x scripts/travis/add-key.sh
- chmod +x scripts/travis/remove-key.sh

before_script:
xcodebuild -scheme XcodeTravis clean test
- ./scripts/travis/add-key.sh

script:
-xcodebuild -project XcodeTravis.xcodeproj -scheme XcodeTravis -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
-xctool test -workspace XcodeTravis.xcodeproj -scheme TravisExampleTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
"./run-tests.sh"

after_script:
- ./scripts/travis/remove-key.sh

env:
global:
- APPNAME="NAME_OF_THE_APP"
- 'DEVELOPER_NAME="iPhone Distribution: NAME_OF_THE_DEVELOPER (CODE)"'
- PROFILE_UUID=PROVISIONING_PROFILE_UUID