language: objective-c
before_install:
- chmod +x scripts/add-key.sh
- chmod +x scripts/remove-key.sh
- chmod +x scripts/update-bundle.sh
- chmod +x scripts/sign-and-upload.sh
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/TravisExample_Ad_Hoc.mobileprovision.enc
  -d -a -out scripts/profile/TravisExample_Ad_Hoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
script:
- xcodebuild -project XcodeTravis.xcodeproj -target XcodeTravis -sdk iphoneos -configuration
  Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
- xcodebuild test -project XcodeTravis.xcodeproj  -scheme XcodeTravis  -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
env:
  global:
  - APP_NAME="XcodeTravis"
  - 'DEVELOPER_NAME="iPhone Distribution: V2 Solutions (JTKBCAGUVC)"'
  - PROFILE_NAME="TravisExample_Ad_Hoc"
  - secure: W4RpPjzupuc8XFKARc+9HQSEabjTeXh8HPukb0N62IXJqAMbFlhexsDvlb1O83JM++ELMCgHR3x9QDVJuGafIwhtxF5N6ByJT9ys0V5w8BHnP7H5aOc42aI39Nylz2rkk0OEfuEU5qGFzVwCIjz4FygPYNVh3XMGw5A2uzX36R8=
  - secure: WbjM7All5bpmo8BF71DANTDZ3+O2zpAeGxgFZQvhR1lJjI+i890ZmBFawaHCqCQ9SHFDNpM1jhczDJ4yp713rg6CZYbAzerB9miFsj6v9rwiBI5MsHb7Rs0aUftikXYItKEAfz/0xnrs7lvtM48bzGqkFmaeXxO4El4ZxjluL6k=
  - secure: aqijYfmU5londL0eeSwQjktAFiMt9X5VYIspj8jsrB5BZXCw7Mgn7SEwXhZAh8K6AQJ9LV6VAKqLK54fCawLeTbPKWf/Q6DOtJOV0235QSb9LwpDIvMX4gr/TV02anQ/RcGSOVVbJQy+iiVkitD7FjUMIyCOQH1oNmiO7hhihlI=
  - secure: FQIzr+etOa65NVEfpFo0k1LohGCPms2qe0oOtOLgahEAY4Meo0ApoMx/6zw2crhINzIZTm4NDAipcZva7B9o48NPsNU4nx9Y9PwE4jrr74sKEwupEaHHJHBMz5Y1RqgEZbfUPhflRgyO875dqF9iKOaF5Ys5LgMbMxdu6tmksTk=
