language: objective-c
before_install:
- chmod +x scripts/travis/add-key.sh
- chmod +x scripts/travis/remove-key.sh
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/travis/Profile/V2Inc_Universal_Disribution.mobileprovision.enc
  -d -a -out scripts/travis/Profile/V2Inc_Universal_Disribution.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/travis/Certificates/DistribCertificates.cer.enc
  -d -a -out scripts/travis/Certificates/DistribCertificates.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/travis/Certificates/Certificates-Distribkey.p12.enc
  -d -a -out scripts/travis/Certificates/Certificates-Distribkey.p12
- ./scripts/travis/add-key.sh
script:
- xcodebuild -project XcodeTravis.xcodeproj -target XcodeTravis -sdk iphoneos -configuration
  Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
- xcodebuild test -project XcodeTravis.xcodeproj  -scheme XcodeTravis  -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
after_script:
- ./scripts/travis/remove-key.sh
env:
  global:
  - APP_NAME="XcodeTravis"
  - 'DEVELOPER_NAME="iPhone Distribution: V2 Solutions (JTKBCAGUVC)"'
  - PROFILE_NAME="V2Inc_Universal_Disribution"
  - secure: itTBbg+b/FZRqG4R8fVDvu7YpbvregmL0hUR42FJqBsi0LQ9tWdB4agIIoGG+SkvyW4lEjb9qXBoGuv78uuvPD6dN4SWnk35DaUmmig3P0bjyTUJRUzdlbotD9uzvmL7b7p+tZDro43t8OrgMudukm+xXO72QYiNyMGBemXptgU=
  - secure: Ljd69JO2YkoBi93o00W/Seh7Uc24aaB68Qr4lC/9hb6q73JeoAe76QZ6PaCcCsPIaWtK+zuI2CBDGEOSvxJ1wZ8kMDG7BWhUak27W/8d7duHnkNmGcl3jQ0JNkS4+mO+mgbCtabGp9PsDiB9DODakgA3+YVecf3uFFUVlTe4j8c=
