language: objective-c
before_install:
# print version of os x
#- sw_vers
#install xctool
- brew update
- brew remove xctool
- brew install xctool
- chmod +x scripts/travis/add-key.sh
- chmod +x scripts/travis/remove-key.sh
before_script:
xcodebuild -scheme XcodeTravis clean test
xcodebuild -project XcodeTravis.xcodeproj -target XcodeTravis -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- ./scripts/travis/add-key.sh
before_install:
script:
"./run-tests.sh"
xcode_project: XcodeTravis.xcodeproj
xcode_scheme: XcodeTravis
after_script:
- ./scripts/travis/remove-key.sh
after_success:
env:
global:
- APPNAME="NAME_OF_THE_APP"
- 'DEVELOPER_NAME="iPhone Distribution: NAME_OF_THE_DEVELOPER (CODE)"'
- PROFILE_UUID=PROVISIONING_PROFILE_UUID