language: objective-c
before_install:
- chmod +x scripts/add-key.sh
- chmod +x scripts/remove-key.sh
- chmod +x scripts/update-bundle.sh
- chmod +x scripts/sign-and-upload.sh
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/TravisExample_Ad_Hoc.mobileprovision.enc
  -d -a -out scripts/profile/TravisExample_Ad_Hoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
script:
- xcodebuild -project XcodeTravis.xcodeproj -target XcodeTravis -sdk iphoneos -configuration
  Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
- xcodebuild test -project XcodeTravis.xcodeproj  -scheme XcodeTravis  -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
env:
  global:
  - APP_NAME="XcodeTravis"
  - 'DEVELOPER_NAME="iPhone Distribution: V2 Solutions (JTKBCAGUVC)"'
  - PROFILE_NAME="TravisExample_Ad_Hoc"
  - secure: W4RpPjzupuc8XFKARc+9HQSEabjTeXh8HPukb0N62IXJqAMbFlhexsDvlb1O83JM++ELMCgHR3x9QDVJuGafIwhtxF5N6ByJT9ys0V5w8BHnP7H5aOc42aI39Nylz2rkk0OEfuEU5qGFzVwCIjz4FygPYNVh3XMGw5A2uzX36R8=
  - secure: WbjM7All5bpmo8BF71DANTDZ3+O2zpAeGxgFZQvhR1lJjI+i890ZmBFawaHCqCQ9SHFDNpM1jhczDJ4yp713rg6CZYbAzerB9miFsj6v9rwiBI5MsHb7Rs0aUftikXYItKEAfz/0xnrs7lvtM48bzGqkFmaeXxO4El4ZxjluL6k=
  - secure: ISoXRIEkz1giSi5cYT6pFHOO+dUTUUIaU5TWQOFuO7ixB39XzxExNWsC5OYnm9xJHN1eSAZYPy17OCIPysGKVVxTx2zNx/c6bcFe0BIP43SZqT+qvmLcg7/wKoLzyMX8vJPM1sqBa544CseH0l/qwAoOnGL/T2bGFMNTBw6OBG8=
  - secure: BwX591cxFOH5YUsO0TCEqhPEf+q+mDh6Ghy1X77ce7TY+dXiY9hDXnIA4Z8I+3CgnADFswHAlI6kUY0Fp5HTzxyY39pu5Crc5dmstWn0aCaV0VbldktxPa7nUqeM979FdRTCQd75tCiNPWny/cNrmLVEqhJ3im/6TSiLcb7wIso=