language: objective-c
before_install:
- brew update
- brew remove xctool
- brew install xctool
- chmod +x scripts/travis/add-key.sh
- chmod +x scripts/travis/remove-key.sh
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/travis/Profile/V2Inc_Development_Wildcard.mobileprovision.enc
  -d -a -out scripts/travis/Profile/V2Inc_Development_Wildcard.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/travis/Certificates/Certificate.cer.enc
  -d -a -out scripts/travis/Certificates/Certificate.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/travis/Certificates/Certificates-key.p12.enc
  -d -a -out scripts/travis/Certificates/Certificates-key.p12
- ./scripts/travis/add-key.sh
script:
- xcodebuild test -project XcodeTravis.xcodeproj  -scheme XcodeTravis  -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
after_script:
- ./scripts/travis/remove-key.sh
env:
  global:
  - secure: GgPTWYUQj0Xg139CajM9DguLG0EeItIvOt6+cWLVpeuye8dDN4cEcP777cu/fZ2K9Ilug24qUN44Jijw3DGzov4iyhcGon4ELZjGplz5b/bvOuPe5PEZaCwxDBnlgSWOExZxc6fOUN5vtx3gNYDc0U56SsBkmx/QMqSCBy20mOY=
  - secure: eHgnbL513I3ffnF8itbvTXM2+z/RYq7QWBN/b72mkhFOEDPJ/m2L0nSx8Wtyqq1NC/hKwv0KsjDnVbWRCVswlghznvwejXOk4gS53Mwe1/i/kcmzVvm7q2hBDpb+aLhOTVe0zWqVOiSFrbWUigzLKdvA+/xsKqH0MGmjBKNB1Kc=
  - APP_NAME="XcodeTravis"
  - 'DEVELOPER_NAME="iPhone Developer: Ajay Sharma (TCGKB2TTPP)"'
  - PROFILE_NAME="V2Inc_Development_Wildcard"
